<?php

/**
 * @file
 * Liveblog pusher module file.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function liveblog_pusher_node_view(array &$build, Node $node, EntityViewDisplayInterface $display, $view_mode) {
  // TODO: abstract this to the parent liveblog module.
  if ($display->getComponent('liveblog_posts')
        && Drupal::config('liveblog.settings')->get('notification_channel') == 'liveblog_pusher') {

    $config = Drupal::config('liveblog.notification_channel.liveblog_pusher');
    $key = $config->get('key');
    $channel_prefix = Drupal::config('liveblog.settings')->get('channel_prefix');

    $build['liveblog_posts']['#attached']['library'][] = 'liveblog_pusher/pusher';
    $build['liveblog_posts']['#attached']['drupalSettings']['liveblog_pusher'] = [
      'key' => $key,
      'channel' => "$channel_prefix-{$node->id()}",
      'cluster' => $config->get('cluster'),
    ];
  }
}
