<?php

/**
 * @file
 * The module file.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_entity_extra_field_info().
 */
function liveblog_entity_extra_field_info() {
  $fields['node']['liveblog']['display']['liveblog_posts'] = [
    'label' => t('Liveblog posts'),
    'description' => t('List of the related liveblog posts.'),
    'weight' => 4,
  ];

  return $fields;
}

/**
 * Implements hook_ENTITY_TYPE_view() for user entities.
 */
function liveblog_node_view(array &$build, Node $node, EntityViewDisplayInterface $display) {
  if ($display->getComponent('liveblog_posts')) {
    $build['liveblog_posts'] = [
      '#theme' => 'liveblog_posts',
      '#node' => $node,
      // @todo: Add js, css assets.
    ];
  }
}

/**
 * Implements hook_theme().
 */
function liveblog_theme() {
  return [
    'liveblog_post' => [
      'render element' => 'elements',
    ],
    'liveblog_posts' => [
      'variables' => [
        'node' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function template_preprocess_liveblog_post(&$variables) {
  /* @var \Drupal\liveblog\Entity\LiveblogPost $post */
  $post = $variables['elements']['#liveblog_post'];
  $variables['highlight'] = $post->highlight->value;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function template_preprocess_liveblog_posts(&$variables) {
  /* @var $node Drupal\node\Entity\Node */
  $node = $variables['node'];

  if ($node->field_status->value) {
    // Embed related posts of the active liveblog.
    $views_content = views_embed_view('liveblog_posts', 'liveblog_posts', $node->id());

    $account = \Drupal::currentUser();
    // Embed liveblog post add form.
    if ($account->hasPermission('add liveblog_post entity')) {
      $entity = \Drupal::entityTypeManager()->getStorage('liveblog_post')->create([]);
      $form_object = \Drupal::entityTypeManager()
        ->getFormObject('liveblog_post', 'add')
        ->setEntity($entity);
      $form = \Drupal::formBuilder()->getForm($form_object);
      $variables['form'] = $form;
    }
  }
  else {
    // Embed archive of related posts if the liveblog is not active anymore.
    $views_content = views_embed_view('liveblog_posts', 'liveblog_posts_archive', $node->id());
  }
  // Embed liveblog posts views.
  $variables['posts'] = \Drupal::service('renderer')->render($views_content);
}
